# IDRA Day 12 - Used Car Data Preprocessing

## Assignment

Used Car Data Preprocessing using Python and Pandas.

### Objectives
- Load and understand the dataset
- Check missing values and duplicates
- Identify and handle outliers
- Separate features and target
- Split data into training and testing sets
- Encode categorical variables
- Scale numerical features
- Avoid data leakage
- Verify the processed dataset
- Export the preprocessed dataset

## Tools Used
- Python
- Pandas
- NumPy
- Scikit-learn

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [5]:
df = pd.read_csv('/content/Day12_Used_Car_Preprocessing_Dataset.csv')

df

,Car_ID,Brand,Year,Mileage_Km,Engine_CC,Power_BHP,Fuel_Type,Transmission,City,Seller_Type,Condition,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
0,CAR0001,Skoda,2021,69708,1152,128.8,Diesel,Manual,Lucknow,Individual,Good,1,0,72,6.38
1,CAR0002,Toyota,2020,88881,903,146.5,Diesel,Automatic,Chandigarh,Individual,Good,1,0,87,4.83
2,CAR0003,Volkswagen,2021,43646,1446,185.9,Diesel,Automatic,Hyderabad,Individual,Very Good,2,0,90,7.30
3,CAR0004,Tata,2019,70847,2069,148.8,Petrol,Manual,Lucknow,Individual,Excellent,3,0,66,3.82
4,CAR0005,Tata,2016,101228,1657,206.0,Petrol,Automatic,Ahmedabad,Dealer,Very Good,2,0,84,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,CAR0316,Mahindra,2014,151557,1186,131.9,Petrol,Automatic,Lucknow,Dealer,Fair,2,0,94,1.20
316,CAR0317,Volkswagen,2020,60512,1308,135.6,Petrol,Automatic,Delhi,Individual,Excellent,1,2,95,5.93
317,CAR0318,Mahindra,2022,76484,1038,139.6,Diesel,Automatic,Delhi,Dealer,Good,1,1,69,5.30
318,CAR0319,Hyundai,2019,125681,1327,164.3,Diesel,Automatic,Delhi,Dealer,Very Good,1,0,59,3.68
319,CAR0320,Honda,2020,71321,1266,95.0,Diesel,Manual,Ahmedabad,Individual,Excellent,2,0,97,5.57

In [3]:
df.shape

(320, 15)

In [4]:
df.head()

,Car_ID,Brand,Year,Mileage_Km,Engine_CC,Power_BHP,Fuel_Type,Transmission,City,Seller_Type,Condition,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
0,CAR0001,Skoda,2021,69708,1152,128.8,Diesel,Manual,Lucknow,Individual,Good,1,0,72,6.38
1,CAR0002,Toyota,2020,88881,903,146.5,Diesel,Automatic,Chandigarh,Individual,Good,1,0,87,4.83
2,CAR0003,Volkswagen,2021,43646,1446,185.9,Diesel,Automatic,Hyderabad,Individual,Very Good,2,0,90,7.30
3,CAR0004,Tata,2019,70847,2069,148.8,Petrol,Manual,Lucknow,Individual,Excellent,3,0,66,3.82
4,CAR0005,Tata,2016,101228,1657,206.0,Petrol,Automatic,Ahmedabad,Dealer,Very Good,2,0,84,1.93

In [6]:
df.tail()

,Car_ID,Brand,Year,Mileage_Km,Engine_CC,Power_BHP,Fuel_Type,Transmission,City,Seller_Type,Condition,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
315,CAR0316,Mahindra,2014,151557,1186,131.9,Petrol,Automatic,Lucknow,Dealer,Fair,2,0,94,1.20
316,CAR0317,Volkswagen,2020,60512,1308,135.6,Petrol,Automatic,Delhi,Individual,Excellent,1,2,95,5.93
317,CAR0318,Mahindra,2022,76484,1038,139.6,Diesel,Automatic,Delhi,Dealer,Good,1,1,69,5.30
318,CAR0319,Hyundai,2019,125681,1327,164.3,Diesel,Automatic,Delhi,Dealer,Very Good,1,0,59,3.68
319,CAR0320,Honda,2020,71321,1266,95.0,Diesel,Manual,Ahmedabad,Individual,Excellent,2,0,97,5.57

In [8]:
df.columns

Index(['Car_ID', 'Brand', 'Year', 'Mileage_Km', 'Engine_CC', 'Power_BHP',
       'Fuel_Type', 'Transmission', 'City', 'Seller_Type', 'Condition',
       'Previous_Owners', 'Accidents_Reported', 'Service_Score',
       'Resale_Price_Lakh'],
      dtype='object')

In [9]:
df.dtypes

Car_ID                 object
Brand                  object
Year                    int64
Mileage_Km              int64
Engine_CC               int64
Power_BHP             float64
Fuel_Type              object
Transmission           object
City                   object
Seller_Type            object
Condition              object
Previous_Owners         int64
Accidents_Reported      int64
Service_Score           int64
Resale_Price_Lakh     float64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Car_ID              320 non-null    object
 1   Brand               320 non-null    object
 2   Year                320 non-null    int64
 3   Mileage_Km          320 non-null    int64
 4   Engine_CC           320 non-null    int64
 5   Power_BHP           320 non-null    float64
 6   Fuel_Type           320 non-null    object
 7   Transmission        320 non-null    object
 8   City                320 non-null    object
 9   Seller_Type         320 non-null    object
 10  Condition           320 non-null    object
 11  Previous_Owners     320 non-null    int64
 12  Accidents_Reported  320 non-null    int64
 13  Service_Score       320 non-null    int64
 14  Resale_Price_Lakh   320 non-null    float64
dtypes: float64(2), int64(6), object(7)
memory usage: 37.6+ KB

In [11]:
df.describe()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
count,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000
mean,2019.537500,74110.203125,1346.703125,150.489688,1.668750,0.243750,76.203125,4.963031
std,3.341367,38885.260771,543.408160,36.665353,0.865369,0.528164,12.745864,3.359259
min,2014.000000,700.000000,600.000000,51.400000,1.000000,0.000000,55.000000,1.200000
25%,2017.000000,46323.250000,1004.750000,128.450000,1.000000,0.000000,64.750000,2.277500
50%,2020.000000,72718.500000,1303.000000,150.750000,1.000000,0.000000,77.000000,4.610000
75%,2022.000000,97951.500000,1635.250000,171.475000,2.000000,0.000000,87.000000,6.835000
max,2025.000000,320000.000000,5000.000000,390.000000,4.000000,2.000000,98.000000,28.500000

In [12]:
df.isnull().sum()

Car_ID                0
Brand                 0
Year                  0
Mileage_Km            0
Engine_CC             0
Power_BHP             0
Fuel_Type             0
Transmission          0
City                  0
Seller_Type           0
Condition             0
Previous_Owners       0
Accidents_Reported    0
Service_Score         0
Resale_Price_Lakh     0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
for column in df.select_dtypes(include='object').columns:
    print(column)
    print(df[column].unique())
    print()

Car_ID
['CAR0001' 'CAR0002' 'CAR0003' 'CAR0004' 'CAR0005' 'CAR0006' 'CAR0007'
 'CAR0008' 'CAR0009' 'CAR0010' 'CAR0011' 'CAR0012' 'CAR0013' 'CAR0014'
 'CAR0015' 'CAR0016' 'CAR0017' 'CAR0018' 'CAR0019' 'CAR0020' 'CAR0021'
 'CAR0022' 'CAR0023' 'CAR0024' 'CAR0025' 'CAR0026' 'CAR0027' 'CAR0028'
 'CAR0029' 'CAR0030' 'CAR0031' 'CAR0032' 'CAR0033' 'CAR0034' 'CAR0035'
 'CAR0036' 'CAR0037' 'CAR0038' 'CAR0039' 'CAR0040' 'CAR0041' 'CAR0042'
 'CAR0043' 'CAR0044' 'CAR0045' 'CAR0046' 'CAR0047' 'CAR0048' 'CAR0049'
 'CAR0050' 'CAR0051' 'CAR0052' 'CAR0053' 'CAR0054' 'CAR0055' 'CAR0056'
 'CAR0057' 'CAR0058' 'CAR0059' 'CAR0060' 'CAR0061' 'CAR0062' 'CAR0063'
 'CAR0064' 'CAR0065' 'CAR0066' 'CAR0067' 'CAR0068' 'CAR0069' 'CAR0070'
 'CAR0071' 'CAR0072' 'CAR0073' 'CAR0074' 'CAR0075' 'CAR0076' 'CAR0077'
 'CAR0078' 'CAR0079' 'CAR0080' 'CAR0081' 'CAR0082' 'CAR0083' 'CAR0084'
 'CAR0085' 'CAR0086' 'CAR0087' 'CAR0088' 'CAR0089' 'CAR0090' 'CAR0091'
 'CAR0092' 'CAR0093' 'CAR0094' 'CAR0095' 'CAR0096' 'CAR0097' 'CAR0098'
 'CAR0099' 'CAR0100' 'CAR0101' 'CAR0102' 'CAR0103' 'CAR0104' 'CAR0105'
 'CAR0106' 'CAR0107' 'CAR0108' 'CAR0109' 'CAR0110' 'CAR0111' 'CAR0112'
 'CAR0113' 'CAR0114' 'CAR0115' 'CAR0116' 'CAR0117' 'CAR0118' 'CAR0119'
 'CAR0120' 'CAR0121' 'CAR0122' 'CAR0123' 'CAR0124' 'CAR0125' 'CAR0126'
 'CAR0127' 'CAR0128' 'CAR0129' 'CAR0130' 'CAR0131' 'CAR0132' 'CAR0133'
 'CAR0134' 'CAR0135' 'CAR0136' 'CAR0137' 'CAR0138' 'CAR0139' 'CAR0140'
 'CAR0141' 'CAR0142' 'CAR0143' 'CAR0144' 'CAR0145' 'CAR0146' 'CAR0147'
 'CAR0148' 'CAR0149' 'CAR0150' 'CAR0151' 'CAR0152' 'CAR0153' 'CAR0154'
 'CAR0155' 'CAR0156' 'CAR0157' 'CAR0158' 'CAR0159' 'CAR0160' 'CAR0161'
 'CAR0162' 'CAR0163' 'CAR0164' 'CAR0165' 'CAR0166' 'CAR0167' 'CAR0168'
 'CAR0169' 'CAR0170' 'CAR0171' 'CAR0172' 'CAR0173' 'CAR0174' 'CAR0175'
 'CAR0176' 'CAR0177' 'CAR0178' 'CAR0179' 'CAR0180' 'CAR0181' 'CAR0182'
 'CAR0183' 'CAR0184' 'CAR0185' 'CAR0186' 'CAR0187' 'CAR0188' 'CAR0189'
 'CAR0190' 'CAR0191' 'CAR0192' 'CAR0193' 'CAR0194' 'CAR0195' 'CAR0196'
 'CAR0197' 'CAR0198' 'CAR0199' 'CAR0200' 'CAR0201' 'CAR0202' 'CAR0203'
 'CAR0204' 'CAR0205' 'CAR0206' 'CAR0207' 'CAR0208' 'CAR0209' 'CAR0210'
 'CAR0211' 'CAR0212' 'CAR0213' 'CAR0214' 'CAR0215' 'CAR0216' 'CAR0217'
 'CAR0218' 'CAR0219' 'CAR0220' 'CAR0221' 'CAR0222' 'CAR0223' 'CAR0224'
 'CAR0225' 'CAR0226' 'CAR0227' 'CAR0228' 'CAR0229' 'CAR0230' 'CAR0231'
 'CAR0232' 'CAR0233' 'CAR0234' 'CAR0235' 'CAR0236' 'CAR0237' 'CAR0238'
 'CAR0239' 'CAR0240' 'CAR0241' 'CAR0242' 'CAR0243' 'CAR0244' 'CAR0245'
 'CAR0246' 'CAR0247' 'CAR0248' 'CAR0249' 'CAR0250' 'CAR0251' 'CAR0252'
 'CAR0253' 'CAR0254' 'CAR0255' 'CAR0256' 'CAR0257' 'CAR0258' 'CAR0259'
 'CAR0260' 'CAR0261' 'CAR0262' 'CAR0263' 'CAR0264' 'CAR0265' 'CAR0266'
 'CAR0267' 'CAR0268' 'CAR0269' 'CAR0270' 'CAR0271' 'CAR0272' 'CAR0273'
 'CAR0274' 'CAR0275' 'CAR0276' 'CAR0277' 'CAR0278' 'CAR0279' 'CAR0280'
 'CAR0281' 'CAR0282' 'CAR0283' 'CAR0284' 'CAR0285' 'CAR0286' 'CAR0287'
 'CAR0288' 'CAR0289' 'CAR0290' 'CAR0291' 'CAR0292' 'CAR0293' 'CAR0294'
 'CAR0295' 'CAR0296' 'CAR0297' 'CAR0298' 'CAR0299' 'CAR0300' 'CAR0301'
 'CAR0302' 'CAR0303' 'CAR0304' 'CAR0305' 'CAR0306' 'CAR0307' 'CAR0308'
 'CAR0309' 'CAR0310' 'CAR0311' 'CAR0312' 'CAR0313' 'CAR0314' 'CAR0315'
 'CAR0316' 'CAR0317' 'CAR0318' 'CAR0319' 'CAR0320']

Brand
['Skoda' 'Toyota' 'Volkswagen' 'Tata' 'Maruti' 'Kia' 'Honda' 'Renault'
 'Mahindra' 'Hyundai']

Fuel_Type
['Diesel' 'Petrol' 'CNG' 'Electric']

Transmission
['Manual' 'Automatic']

City
['Lucknow' 'Chandigarh' 'Hyderabad' 'Ahmedabad' 'Delhi' 'Bengaluru'
 'Mumbai' 'Jaipur' 'Kochi' 'Pune']

Seller_Type
['Individual' 'Dealer' 'Certified Dealer']

Condition
['Good' 'Very Good' 'Excellent' 'Fair' 'Poor']

In [15]:
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

categorical_columns = df.select_dtypes(include='object').columns.tolist()

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numerical Columns:
['Year', 'Mileage_Km', 'Engine_CC', 'Power_BHP', 'Previous_Owners', 'Accidents_Reported', 'Service_Score', 'Resale_Price_Lakh']

Categorical Columns:
['Car_ID', 'Brand', 'Fuel_Type', 'Transmission', 'City', 'Seller_Type', 'Condition']

In [16]:
df = df.drop('Car_ID', axis=1)

df.head()

,Brand,Year,Mileage_Km,Engine_CC,Power_BHP,Fuel_Type,Transmission,City,Seller_Type,Condition,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
0,Skoda,2021,69708,1152,128.8,Diesel,Manual,Lucknow,Individual,Good,1,0,72,6.38
1,Toyota,2020,88881,903,146.5,Diesel,Automatic,Chandigarh,Individual,Good,1,0,87,4.83
2,Volkswagen,2021,43646,1446,185.9,Diesel,Automatic,Hyderabad,Individual,Very Good,2,0,90,7.30
3,Tata,2019,70847,2069,148.8,Petrol,Manual,Lucknow,Individual,Excellent,3,0,66,3.82
4,Tata,2016,101228,1657,206.0,Petrol,Automatic,Ahmedabad,Dealer,Very Good,2,0,84,1.93

## Outlier Detection Using IQR

The Interquartile Range (IQR) method is used to identify outliers.

IQR = Q3 - Q1

Lower limit = Q1 - 1.5 × IQR

Upper limit = Q3 + 1.5 × IQR

Values below the lower limit or above the upper limit are considered outliers.

In [17]:
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

for column in numerical_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_limit) | (df[column] > upper_limit)]

    print(column, ":", len(outliers), "outliers")

Year : 0 outliers
Mileage_Km : 2 outliers
Engine_CC : 6 outliers
Power_BHP : 7 outliers
Previous_Owners : 14 outliers
Accidents_Reported : 63 outliers
Service_Score : 0 outliers
Resale_Price_Lakh : 5 outliers

In [18]:
for column in numerical_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    df[column] = df[column].clip(lower=lower_limit, upper=upper_limit)

In [19]:
for column in numerical_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_limit) | (df[column] > upper_limit)]

    print(column, ":", len(outliers), "outliers")

Year : 0 outliers
Mileage_Km : 0 outliers
Engine_CC : 0 outliers
Power_BHP : 0 outliers
Previous_Owners : 0 outliers
Accidents_Reported : 0 outliers
Service_Score : 0 outliers
Resale_Price_Lakh : 0 outliers

In [20]:
X = df.drop('Resale_Price_Lakh', axis=1)

y = df['Resale_Price_Lakh']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (320, 13)
Target shape: (320,)

In [21]:
X.head()

,Brand,Year,Mileage_Km,Engine_CC,Power_BHP,Fuel_Type,Transmission,City,Seller_Type,Condition,Previous_Owners,Accidents_Reported,Service_Score
0,Skoda,2021,69708.0,1152,128.8,Diesel,Manual,Lucknow,Individual,Good,1.0,0,72
1,Toyota,2020,88881.0,903,146.5,Diesel,Automatic,Chandigarh,Individual,Good,1.0,0,87
2,Volkswagen,2021,43646.0,1446,185.9,Diesel,Automatic,Hyderabad,Individual,Very Good,2.0,0,90
3,Tata,2019,70847.0,2069,148.8,Petrol,Manual,Lucknow,Individual,Excellent,3.0,0,66
4,Tata,2016,101228.0,1657,206.0,Petrol,Automatic,Ahmedabad,Dealer,Very Good,2.0,0,84

In [22]:
y.head()

0    6.38
1    4.83
2    7.30
3    3.82
4    1.93
Name: Resale_Price_Lakh, dtype: float64

## Train-Test Split

The dataset is divided into:
- 80% training data
- 20% testing data

The random_state is used so that the same split can be reproduced.

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (256, 13)
Testing data: (64, 13)

In [24]:
categorical_columns = X_train.select_dtypes(include='object').columns.tolist()

numerical_columns = X_train.select_dtypes(include=np.number).columns.tolist()

print("Categorical Columns:")
print(categorical_columns)

print("\nNumerical Columns:")
print(numerical_columns)

Categorical Columns:
['Brand', 'Fuel_Type', 'Transmission', 'City', 'Seller_Type', 'Condition']

Numerical Columns:
['Year', 'Mileage_Km', 'Engine_CC', 'Power_BHP', 'Previous_Owners', 'Accidents_Reported', 'Service_Score']

## Encoding Categorical Variables

The categorical variables are nominal variables, so One-Hot Encoding is suitable.

One-Hot Encoding converts categories into separate numerical columns.

The encoder is fitted only on the training data to prevent data leakage.

In [25]:
encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

X_train_encoded = encoder.fit_transform(X_train[categorical_columns])

X_test_encoded = encoder.transform(X_test[categorical_columns])

In [26]:
encoder.fit_transform(X_train[categorical_columns])

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
encoder.transform(X_test[categorical_columns])

array([[0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Feature Scaling

StandardScaler is used to standardize the numerical features.

The scaler is fitted only on the training data and then used to transform both training and testing data.

This prevents data leakage.

In [27]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train[numerical_columns])

X_test_scaled = scaler.transform(X_test[numerical_columns])

In [28]:
X_train_processed = np.hstack([
    X_train_scaled,
    X_train_encoded
])

X_test_processed = np.hstack([
    X_test_scaled,
    X_test_encoded
])

print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (256, 41)
Processed testing shape: (64, 41)

In [29]:
encoded_columns = encoder.get_feature_names_out(categorical_columns)

print(encoded_columns)

['Brand_Honda' 'Brand_Hyundai' 'Brand_Kia' 'Brand_Mahindra' 'Brand_Maruti'
 'Brand_Renault' 'Brand_Skoda' 'Brand_Tata' 'Brand_Toyota'
 'Brand_Volkswagen' 'Fuel_Type_CNG' 'Fuel_Type_Diesel'
 'Fuel_Type_Electric' 'Fuel_Type_Petrol' 'Transmission_Automatic'
 'Transmission_Manual' 'City_Ahmedabad' 'City_Bengaluru' 'City_Chandigarh'
 'City_Delhi' 'City_Hyderabad' 'City_Jaipur' 'City_Kochi' 'City_Lucknow'
 'City_Mumbai' 'City_Pune' 'Seller_Type_Certified Dealer'
 'Seller_Type_Dealer' 'Seller_Type_Individual' 'Condition_Excellent'
 'Condition_Fair' 'Condition_Good' 'Condition_Poor' 'Condition_Very Good']

In [30]:
processed_columns = numerical_columns + encoded_columns.tolist()

print("Number of processed columns:", len(processed_columns))

Number of processed columns: 41

In [31]:
X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=processed_columns,
    index=X_train.index
)

X_train_processed_df.head()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Brand_Honda,Brand_Hyundai,Brand_Kia,...,City_Mumbai,City_Pune,Seller_Type_Certified Dealer,Seller_Type_Dealer,Seller_Type_Individual,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Condition_Very Good
132,-0.486391,-0.225904,-0.322825,0.303144,-0.755752,0.0,-0.454105,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
317,0.725445,0.089296,-0.656909,-0.328921,-0.755752,0.0,-0.614672,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
234,-1.395268,1.115547,-0.120148,0.418918,-0.755752,0.0,-0.534389,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
312,1.028404,-0.195102,0.481202,0.412660,0.484456,0.0,0.188165,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
232,-1.092309,0.706499,0.788558,-0.435309,0.484456,0.0,0.107881,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [32]:
X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=processed_columns,
    index=X_test.index
)

X_test_processed_df.head()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Brand_Honda,Brand_Hyundai,Brand_Kia,...,City_Mumbai,City_Pune,Seller_Type_Certified Dealer,Seller_Type_Dealer,Seller_Type_Individual,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Condition_Very Good
167,-0.486391,0.908183,-1.632432,-0.970374,-0.755752,0.0,-0.373821,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
230,1.331363,-0.926895,0.786331,-0.225663,0.484456,0.0,-1.337226,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
25,-1.092309,0.710145,-1.416391,-0.707535,-0.755752,0.0,1.552989,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
63,-0.486391,0.866416,-1.632432,-0.773244,0.484456,0.0,1.071286,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
9,-1.395268,2.143692,-0.002105,0.099756,-0.755752,0.0,-0.775240,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [34]:
train_processed = X_train_processed_df.copy()

train_processed['Resale_Price_Lakh'] = y_train

test_processed = X_test_processed_df.copy()

test_processed['Resale_Price_Lakh'] = y_test

In [35]:
train_processed.head()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Brand_Honda,Brand_Hyundai,Brand_Kia,...,City_Pune,Seller_Type_Certified Dealer,Seller_Type_Dealer,Seller_Type_Individual,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Condition_Very Good,Resale_Price_Lakh
132,-0.486391,-0.225904,-0.322825,0.303144,-0.755752,0.0,-0.454105,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.26
317,0.725445,0.089296,-0.656909,-0.328921,-0.755752,0.0,-0.614672,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,5.30
234,-1.395268,1.115547,-0.120148,0.418918,-0.755752,0.0,-0.534389,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.23
312,1.028404,-0.195102,0.481202,0.412660,0.484456,0.0,0.188165,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,7.09
232,-1.092309,0.706499,0.788558,-0.435309,0.484456,0.0,0.107881,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.69

In [36]:
test_processed.head()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Brand_Honda,Brand_Hyundai,Brand_Kia,...,City_Pune,Seller_Type_Certified Dealer,Seller_Type_Dealer,Seller_Type_Individual,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Condition_Very Good,Resale_Price_Lakh
167,-0.486391,0.908183,-1.632432,-0.970374,-0.755752,0.0,-0.373821,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.62
230,1.331363,-0.926895,0.786331,-0.225663,0.484456,0.0,-1.337226,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,8.35
25,-1.092309,0.710145,-1.416391,-0.707535,-0.755752,0.0,1.552989,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.11
63,-0.486391,0.866416,-1.632432,-0.773244,0.484456,0.0,1.071286,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.82
9,-1.395268,2.143692,-0.002105,0.099756,-0.755752,0.0,-0.775240,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.20

In [37]:
print("Training data shape:", train_processed.shape)
print("Testing data shape:", test_processed.shape)

Training data shape: (256, 42)
Testing data shape: (64, 42)

In [38]:
print("Missing values in training data:")
print(train_processed.isnull().sum().sum())

print("\nMissing values in testing data:")
print(test_processed.isnull().sum().sum())

Missing values in training data:
0

Missing values in testing data:
0

In [39]:
print("Training duplicates:", train_processed.duplicated().sum())
print("Testing duplicates:", test_processed.duplicated().sum())

Training duplicates: 0
Testing duplicates: 0

In [40]:
train_processed.dtypes

Year                            float64
Mileage_Km                      float64
Engine_CC                       float64
Power_BHP                       float64
Previous_Owners                 float64
Accidents_Reported              float64
Service_Score                   float64
Brand_Honda                     float64
Brand_Hyundai                   float64
Brand_Kia                       float64
Brand_Mahindra                  float64
Brand_Maruti                    float64
Brand_Renault                   float64
Brand_Skoda                     float64
Brand_Tata                      float64
Brand_Toyota                    float64
Brand_Volkswagen                float64
Fuel_Type_CNG                   float64
Fuel_Type_Diesel                float64
Fuel_Type_Electric              float64
Fuel_Type_Petrol                float64
Transmission_Automatic          float64
Transmission_Manual             float64
City_Ahmedabad                  float64
City_Bengaluru                  float64
City_Chandigarh                 float64
City_Delhi                      float64
City_Hyderabad                  float64
City_Jaipur                     float64
City_Kochi                      float64
City_Lucknow                    float64
City_Mumbai                     float64
City_Pune                       float64
Seller_Type_Certified Dealer    float64
Seller_Type_Dealer              float64
Seller_Type_Individual          float64
Condition_Excellent             float64
Condition_Fair                  float64
Condition_Good                  float64
Condition_Poor                  float64
Condition_Very Good             float64
Resale_Price_Lakh               float64
dtype: object

In [41]:
train_processed[numerical_columns].describe()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score
count,2.560000e+02,2.560000e+02,2.560000e+02,2.560000e+02,2.560000e+02,256.0,2.560000e+02
mean,-3.816392e-17,-1.040834e-17,1.214306e-17,-1.734723e-16,-4.163336e-17,0.0,-6.938894e-18
std,1.001959e+00,1.001959e+00,1.001959e+00,1.001959e+00,1.001959e+00,0.0,1.001959e+00
min,-1.698227e+00,-2.046627e+00,-1.632432e+00,-2.697210e+00,-7.557515e-01,0.0,-1.738645e+00
25%,-7.893502e-01,-7.699804e-01,-7.120323e-01,-6.394782e-01,-7.557515e-01,0.0,-8.755947e-01
50%,1.195268e-01,-1.044397e-02,-5.555874e-02,1.214335e-02,-7.557515e-01,0.0,1.078813e-01
75%,7.254448e-01,6.887173e-01,6.944581e-01,6.582891e-01,4.844561e-01,0.0,7.501513e-01
max,1.634322e+00,2.884383e+00,2.779694e+00,2.687859e+00,2.344768e+00,0.0,1.713556e+00

In [42]:
print("Target variable:")
print(y.name)

print("\nTarget values:")
print(y.head())

Target variable:
Resale_Price_Lakh

Target values:
0    6.38
1    4.83
2    7.30
3    3.82
4    1.93
Name: Resale_Price_Lakh, dtype: float64

In [43]:
print("Final Preprocessing Verification")
print("--------------------------------")

print("Original rows:", 320)
print("Training rows:", len(train_processed))
print("Testing rows:", len(test_processed))

print("Training columns:", train_processed.shape[1])
print("Testing columns:", test_processed.shape[1])

print("Training missing values:", train_processed.isnull().sum().sum())
print("Testing missing values:", test_processed.isnull().sum().sum())

print("Training duplicates:", train_processed.duplicated().sum())
print("Testing duplicates:", test_processed.duplicated().sum())

Final Preprocessing Verification
--------------------------------
Original rows: 320
Training rows: 256
Testing rows: 64
Training columns: 42
Testing columns: 42
Training missing values: 0
Testing missing values: 0
Training duplicates: 0
Testing duplicates: 0

In [44]:
train_processed.to_csv(
    'Day12_Preprocessed_Used_Car_Train.csv',
    index=False
)

print("Training dataset saved successfully.")

Training dataset saved successfully.

In [45]:
test_processed.to_csv(
    'Day12_Preprocessed_Used_Car_Test.csv',
    index=False
)

print("Testing dataset saved successfully.")

Testing dataset saved successfully.

In [46]:
from google.colab import files

files.download('Day12_Preprocessed_Used_Car_Train.csv')

In [47]:
files.download('Day12_Preprocessed_Used_Car_Test.csv')

## Observations

1. The dataset contains 320 rows and 15 columns.
2. There are no missing values in the dataset.
3. There are no duplicate rows.
4. Car_ID was removed because it is only an identifier.
5. Outliers were identified using the IQR method.
6. Extreme numerical values were capped using the IQR limits.
7. Resale_Price_Lakh was selected as the target variable.
8. The remaining columns were used as features.
9. The data was split into 80% training data and 20% testing data.
10. Categorical variables were converted into numerical form using One-Hot Encoding.
11. Numerical features were scaled using StandardScaler.
12. The encoder and scaler were fitted only on the training data.
13. The fitted transformations were then applied to the testing data.
14. This approach prevents data leakage from the testing dataset.
15. The processed training and testing datasets were exported as CSV files.

## Conclusion

The Used Car Resale Dataset was successfully preprocessed using Python and Pandas.

The preprocessing workflow included dataset inspection, missing-value checking, duplicate checking, outlier detection and handling, feature-target separation, train-test splitting, categorical encoding, and numerical feature scaling.

The IQR method was used to identify and cap extreme numerical values. Categorical variables were encoded using One-Hot Encoding, while numerical variables were standardized using StandardScaler.

To avoid data leakage, the encoder and scaler were fitted only on the training data and then applied to the testing data.

The final processed training and testing datasets were exported as CSV files and are ready for further machine learning analysis.